import type { Metadata } from "next";

import Header from '@/components/Home/header';
import { Footer } from '@/components/Home/footer';
import "./globals.css"
import faWhatsapp  from "@/../public/whatsapp2.png";
import Image from "next/image";


const WhatsApp = () => {
  return (
    <a href="https://api.whatsapp.com/send?phone=18981268295&text=Olá! Tenho interesse em doces do The Politti's" target="_blank" className="whatsapp-button">
      <Image width={100} height={100} src={faWhatsapp.src} alt="whatsapp"/>
    </a>
  );
};

export const metadata: Metadata = {
  title: "Politti's",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header/>
        {children}
        <WhatsApp/>
        <Footer/>
      </body>
    </html>
  );
}
